### ISSUE TITLE
AWS Build Hangs on Error

### ISSUE THREAD

**Issue by bwp91** [Alliants/alliants-serverless-utils#12]
See example: https://us-east-1.console.aws.amazon.com/codesuite/codebuild/250158614865/projects/apps-evolveme-api-ci-build/build/apps-evolveme-api-ci-build%3Aff71fbf7-f985-4963-9784-4441a7e866b7/?region=us-east-1

```

***** INFO: [CI] Replacing CI database from template...
--
684 | pg_terminate_backend
685 | ----------------------
686 | (0 rows)
687 |  
688 | pg_terminate_backend
689 | ----------------------
690 | (0 rows)
691 |  
692 | psql:./scripts/copy_ci_template.sql:4: ERROR:  database "lifemapsci" is being accessed by other users
693 | DETAIL:  There is 1 other session using the database.
694 | psql:./scripts/copy_ci_template.sql:6: ERROR:  database "lifemapsci" already exists
695 | ***** INFO: Pruning old versions
696 | ✔ Pruning of functions complete
697 | ***** INFO: Deploying database migration function...
698 |  
699 | Deploying function migrate-db to stage ci (us-east-1)
700 | ✘ [ERROR] Could not resolve "src/handlers/adminSupportGetUserByApiKey.js"
701 |  
702 | Environment: linux, node 20.14.0, framework 3.39.0 (local), plugin 7.2.3, SDK 4.5.1
703 | Docs:        docs.serverless.com
704 | Support:     forum.serverless.com
705 | Bugs:        github.com/serverless/serverless/issues
706 |  
707 | Error:
708 | Error: Build failed with 1 error:
709 | error: Could not resolve "src/handlers/adminSupportGetUserByApiKey.js"
710 | at failureErrorWithLog (/codebuild/output/src2195107836/src/node_modules/esbuild/lib/main.js:1472:15)
711 | at /codebuild/output/src2195107836/src/node_modules/esbuild/lib/main.js:945:25
712 | at runOnEndCallbacks (/codebuild/output/src2195107836/src/node_modules/esbuild/lib/main.js:1315:45)
713 | at buildResponseToResult (/codebuild/output/src2195107836/src/node_modules/esbuild/lib/main.js:943:7)
714 | at /codebuild/output/src2195107836/src/node_modules/esbuild/lib/main.js:955:9
715 | at new Promise (<anonymous>)
716 | at requestCallbacks.on-end (/codebuild/output/src2195107836/src/node_modules/esbuild/lib/main.js:954:54)
717 | at handleRequest (/codebuild/output/src2195107836/src/node_modules/esbuild/lib/main.js:647:17)
718 | at handleIncomingPacket (/codebuild/output/src2195107836/src/node_modules/esbuild/lib/main.js:672:7)
719 | at Socket.readFromStdout (/codebuild/output/src2195107836/src/node_modules/esbuild/lib/main.js:600:7)
720 | at Socket.emit (node:events:519:28)
721 | at Socket.emit (node:domain:488:12)
722 | at addChunk (node:internal/streams/readable:559:12)
723 | at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
724 | at Readable.push (node:internal/streams/readable:390:5)
725 | at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)
726 |  
727 | 1 deprecation found: run 'serverless doctor' for more details
```

The build was just hanging and in the end I stopped it manually. Otherwise it would have stayed running for the 60 minutes before it was 'killed'.

**Comment by bwp91** [comment]
Another example at a different point at

https://us-east-1.console.aws.amazon.com/codesuite/codebuild/250158614865/projects/apps-b2br-api-b2bdev-build/build/apps-b2br-api-b2bdev-build%3Add1281e2-469f-497d-9267-3d529a60ab8d/?region=us-east-1

```
...

Test Files  1 passed (1)
--
346 | Tests  13 passed (13)
347 | Start at  08:39:28
348 | Duration  13.97s (transform 287ms, setup 1ms, collect 943ms, tests 7ms, environment 0ms, prepare 74ms)
349 |  
350 | ***** INFO: Pruning old versions
351 | ✔ Pruning of functions complete
352 | ***** INFO: Deploying database migration function...
353 |  
354 | Deploying function migrate-db to stage b2bdev (us-east-1)
355 | Environment: linux, node 20.14.0, framework 3.39.0 (local), plugin 7.2.3, SDK 4.5.1
356 | Docs:        docs.serverless.com
357 | Support:     forum.serverless.com
358 | Bugs:        github.com/serverless/serverless/issues
359 |  
360 | Error:
361 | Error: The service was stopped
362 | at /codebuild/output/src1407725186/src/node_modules/esbuild/lib/main.js:993:26
363 | at responseCallbacks.<computed> (/codebuild/output/src1407725186/src/node_modules/esbuild/lib/main.js:622:9)
364 | at Socket.afterClose (/codebuild/output/src1407725186/src/node_modules/esbuild/lib/main.js:613:28)
365 | at Socket.emit (node:events:531:35)
366 | at Socket.emit (node:domain:488:12)
367 | at endReadableNT (node:internal/streams/readable:1696:12)
368 | at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
369 |  
370 | 1 deprecation found: run 'serverless doctor' for more details


```

**Comment by tinchoz49** [comment]
fix released in v4
